name: Coco's Concierge deployment
on:
  push:
    branches:
      - main
jobs:
  "Concierge-Deployment":
    runs-on: ubuntu-latest
    steps:
      - name: Cloning and setting up repository on Droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd development

            # Kill the previous Updater nohup service
            kill -9 `pgrep python`

            # Stop and remove repo if it exists
            if [ -d cocos-concierge ];then cd cocos-concierge; docker compose down; cd ../; rm -rf cocos-concierge; fi
            git clone --depth 1 --branch main git@github.com:neutonfoo/cocos-concierge.git
            cd cocos-concierge

            # Start the Updater service
            cd updater
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
            nohup python app.py >/dev/null 2>&1 &
            cd ../

            # Start reverse-proxy and certbot
            ./reverse-proxy/nginx-conf-generator.sh
            docker compose up -d --build

# name: GitHub Actions Demo
# run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v3
#       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "ğŸ This job's status is ${{ job.status }}."
